<header>
        <div class="navbar navbar-fixed-top head-wrap" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="/img/sell_me_an_auto_logo.png" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <form class="navbar-form navbar-right" role="form">
                        <span class="contacts">
                            <span>
                                <img src="/img/message_icon.png" />
                            </span><a href="#">Contact Us</a>
                            <span>
                                <img src="/img/chat_icon.png" />
                            </span><a href="#">Live Chat</a>
                        </span>
                        <div class="btn-group login-info">
                            <button type="button" class="btn btn-success btn-lg" style="height:50px;" data-toggle="modal" data-target="#Signin">
                                Login
                            </button>
                        </div>
                    </form>
                </div><!--/.navbar-collapse -->
            </div>
           

        </div>

    </header>
    <section class="main-wrapper">
        <div id="bg">
            <img class="mainimage" src="/img/home_back_wrapper.jpg" />
        </div>
    </section>