<header>
        <div class="navbar navbar-fixed-top head-wrap" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <img src="/img/sell_me_an_auto_logo.png" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <form class="navbar-form navbar-right" role="form">
                        <span class="contacts">
                            <span>
                                <img src="/img/message_icon.png" />
                            </span><a href="/contact-us">Contact Us</a>
                            <span>
                                <img src="/img/chat_icon.png" />
                            </span><a href="/live-chat">Live Chat</a>
                        </span>
                        <?php if ($this->user_profiles) { ?>  
                        <div class="btn-group login-info">
                            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                                <span class="profile-pic"><img src="/img/no-profile-icon.jpg" /></span><?php echo $this->user_profiles['fname']; ?> <?php echo $this->user_profiles['lname']; ?> <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/user/">Edit My Profile</a></li>
                                <li><a href="/user/">Bids</a></li>
                                <li><a href="/user/">Account Settings</a></li>
                                <li class="divider"></li>
                                <li><a href="/user/logout"><strong>Log Out</strong></a></li>
                            </ul>
                    	</div>
                        <?php }else { ?>      
                            <div class="btn-group login-info">
                                <button type="button" class="btn btn-success btn-lg" style="height:50px;" data-toggle="modal" data-target="#Signin">
                                    Login 
                                </button>                            
                            </div>
                        <?php } ?>
                    </form>
                </div><!--/.navbar-collapse -->
            </div>
           <?php if (!$this->register_page) { ?> 
           
            <section class="builder-con">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <button type="button" class="btn dropdown-toggle select-brand" data-toggle="dropdown">
                                Select a Brand <span class="caret"></span>
                            </button>
                            <div class="dropdown-menu ">
                                <div class="container drop-menu">
                                    <div class="col-md-2">
                                        <ul>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="acura" data-name="Acura">Acura</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="audi" data-name="Audi">Audi</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="bmw" data-name="BMW">BMW</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="buick" data-name="Buick">Buick</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="cadillac" data-name="Cadillac">Cadillac</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="chevrolet" data-name="Chevrolet">Chevrolet</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <ul>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="chrysler" data-name="Chrysler">Chrysler</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="dodge" data-name="Dodge">Dodge</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="fiat" data-name="Fiat">FIAT</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="ford" data-name="Ford">Ford</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="gmc" data-name="GMC">GMC</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="honda" data-name="Honda">Honda</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <ul>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="hyundai" data-name="Hyundai">Hyundai</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="infiniti" data-name="Infiniti">Infiniti</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="jaguar" data-name="Jaguar">Jaguar</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="jeep" data-name="Jeep">Jeep</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="kia" data-name="Kia">Kia</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="land-rover" data-name="Land Rover">Land Rover</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <ul>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="lexus" data-name="Lexus">Lexus</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="lincoln" data-name="Lincoln">Lincoln</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="mazda" data-name="Mazda">Mazda</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="mercedes-benz" data-name="Mercedes-Benz">Mercedes-Benz</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="mini" data-name="MINI">MINI</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="mitsubishi" data-name="Mitsubishi">Mitsubishi</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <ul>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="nissan" data-name="Nissan">Nissan</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="porsche" data-name="Porsche">Porsche</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="ram" data-name="Ram">Ram</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="scion" data-name="Scion">Scion</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="smart" data-name="Smart">Smart</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="subaru" data-name="Subaru">Subaru</a></li>

                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <ul>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="toyota" data-name="Toyota">Toyota</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="volkswagen" data-name="Volkswagen">Volkswagen</a></li>
                                            <li><a href="#make-item" class="make-link" data-toggle="modal" data-make="volvo" data-name="Volvo">Volvo</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <span class="start-btn">
                                <a href="#"><img src="/img/start_icon.png" /><span>Start here!</span>Build your vehicle.</a>
                            </span>
                        </div>
                        <div class="col-md-6">
                            <h3 style="text-align:right;"><span>Hassle Free.</span> Zero Negotiation.</h3>
                        </div>
                    </div>
                </div>
            </section>
			<?php } ?>
        </div>

    </header>
    <section class="main-wrapper">
        <div id="bg">
            <img class="mainimage" src="/img/home_back_wrapper.jpg" />
        </div>
    </section>