<input type="hidden" id="style_id" name="style_id" value="<?php echo $this->style_id;?>" />
<input type="hidden" id="car_make" name="car_make" />
<div class="row">
    <div class="col-md-6">
        <img id="car_main_image" src="/public/img/ajax-loader.gif" />
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-8">
                <div class="msrp-con">
                    <span style="font-weight:bold;">MSRP</span>
                    <p id="baseMSRP" class="price" style="font-size: 35px; font-weight: bold; color: #19547B;"><img src="/public/img/ajax-loader.gif" /></p>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <span style="font-weight:bold;">INVOICE PRICE</span>
                        <p id="baseInvoice" style="color: #A3A3A3; font-size: 25px;"><img src="/public/img/ajax-loader.gif" /></p>
                        <select id="car-year" class="form-control"></select>
                    </div>
                    <div class="col-md-7">
                        <span style="font-weight:bold;">FINANCE ESTIMATE</span>
                        <p  id="financing"style="color: #A3A3A3; font-size: 25px;"><img src="/public/img/ajax-loader.gif" /></p>
                        <select id="transmission" class="form-control"></select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div style="border-radius: 50%; border: 6px solid #8BC43F; height: 140px; width: 150px; background-color: #EDF5E0; padding: 30px 25px 0 25px;">
                    <p style=" text-align: center;">We’ve got <span id="dealersCount" style="font-weight: bold; color: #8BC43F;"><img src="/public/img/ajax-loader.gif" /></span> Dealers near  you, and ready to bid.</p>
                    <input id="zipcode" type="hidden" style="padding: 8px 8px; font-weight: bold; text-align: center; width: 80px; margin: 0 auto; margin-left:18px;" value="<?php echo $this->zipcode;?>" readonly="readonly" />
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-lg-12 d-info">
    <button type="button" class="btn btn-warning btn-lg right"><span>Proceed to</span> INTERIOR</button>
    <ul>
        <li>
            <h5>Color</h5>
            <div id="color-box"></div>
            <br clear="all" />
        </li>
        
        <li class="icon-mpg">
            <h5>EPA Est. MPG</h5>
            <p id="mpg"><img src="/public/img/ajax-loader.gif" /> <span>City/Hwy</span></p>
        </li>
        <li class="icon-hp">
            <h5>Horsepower</h5>
            <p id="horsepower"><img src="/public/img/ajax-loader.gif" /></p>
        </li>
        <li class="icon-seat">
            <h5>Seating</h5>
            <p id="numOfSeats"><img src="/public/img/ajax-loader.gif" /></p>
        </li>
    </ul>
</div>


<br clear="all" />    
    
<div id="tab-content" class="tab-content">
    <div class="tab-pane fade in active" id="Exterior">
        <div class="col-lg-12 d-info-con">
        	<h3>Exterior</h3>
        </div>
        <br clear="all" /> 
        <h4>Options</h4> 
        <table id="exterior-options" class="table table-hover">                             
        	<tbody></tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="Interior">
        <div class="col-lg-12 d-info-con"><h3>Interior</h3></div>
        <br clear="all" />  
        <h4>Options</h4> 
        <table id="interior-options" class="table table-hover">                             
        	<tbody></tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="Accessories">
	    <div class="col-lg-12 d-info-con"><h3>Accessories</h3></div>
        <br clear="all" />
        <h4>Options</h4> 
        <table id="accessories-options" class="table table-hover">                             
        	<tbody></tbody>
        </table>  
    </div>
    <div class="tab-pane fade" id="Summary">
        <div class="col-lg-12 d-info-con"><h3>Summary</h3></div>
        <br clear="all" />  
        <p><strong>Under Construction</strong></p>
    </div>
</div>    

<script type="text/x-handlebars-template" id="transmission-template">
	<option>{{trim}} {{transmission.transmissionType}}</option>
</script>
<script type="text/x-handlebars-template" id="car-year-template">
	<option>{{year.year}}</option>
</script>
<script type="text/x-handlebars-template" id="exterior-options-template">
	<tr>
		<td><input type="checkbox" value=""></td>
		<td>{{name}} <span class="price">+ ${{price.baseMSRP}}</span></td>
		<td>Cum sociis natoque penatibus et magnis dis parturient. Vimus magna, accumsan a tortor et porttitor. Donec luctus hendrerit aliquam.ccumsan placerat nisl ac rutrum. Quisque ac egestas nisi. Etiam sed consequat dolor. In ultrices purus placerat massa</td>
	</tr>
</script>

<script type="text/x-handlebars-template" id="color-box-template">
	<p class="color-con" style="float:left; margin-left:10px;  background:#{{colorChips.primary.hex}};" title="{{name}}">&nbsp;</p>
</script>


