<input type="hidden" id="style_id" name="style_id" value="<?php echo $this->style_id;?>" />
<div class="row">
    <div class="col-md-6">
        <img id="car_main_image" src="/public/img/ajax-loader.gif" />
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-8">
                <div class="msrp-con">
                    <span style="font-weight:bold;">MSRP</span>
                    <p id="baseMSRP" class="price" style="font-size: 35px; font-weight: bold; color: #19547B;"><img src="/public/img/ajax-loader.gif" /></p>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <span style="font-weight:bold;">INVOICE PRICE</span>
                        <p id="baseInvoice" style="color: #A3A3A3; font-size: 25px;"><img src="/public/img/ajax-loader.gif" /></p>
                        <select id="car-year" class="form-control"></select>
                    </div>
                    <div class="col-md-7">
                        <span style="font-weight:bold;">FINANCE ESTIMATE</span>
                        <p  id="financing"style="color: #A3A3A3; font-size: 25px;"><img src="/public/img/ajax-loader.gif" /></p>
                        <select id="transmission" class="form-control"></select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div style="border-radius: 50%; border: 6px solid #8BC43F; height: 180px; width: 180px; background-color: #EDF5E0; padding: 30px 25px 0 25px;">
                    <p style=" text-align: center;">We’ve got <span id="number_of_dealers" style="font-weight: bold; color: #8BC43F;"><img src="/public/img/ajax-loader.gif" /> Dealers</span> near  you, and ready to bid.</p>
                    <p id="number_of_dealers_result" style="border:1px solid #ccc; background-color: #fff; padding: 10px 10px; font-weight: bold; text-align: center; width: 80px; margin: 0 auto;"><img src="/public/img/ajax-loader.gif" /></p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-lg-12 d-info">
    <button type="button" class="btn btn-warning btn-lg right"><span>Proceed to</span> INTERIOR</button>
    <ul>
        <li>
            <h5>Color</h5>
            <p class="color-con">&nbsp;</p>

        </li>
        <li class="icon-mpg">
            <h5>EPA Est. MPG</h5>
            <p id="mpg"><img src="/public/img/ajax-loader.gif" /> <span>City/Hwy</span></p>
        </li>
        <li class="icon-hp">
            <h5>Horsepower</h5>
            <p id="horsepower"><img src="/public/img/ajax-loader.gif" /></p>
        </li>
        <li class="icon-seat">
            <h5>Seating</h5>
            <p id="numOfSeats"><img src="/public/img/ajax-loader.gif" /></p>
        </li>
    </ul>
</div>


<div class="col-lg-12 d-info-con">
    <h3>Exterior</h3>
</div>


<div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                               Options
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table table-hover">                             
                                <tbody>
                                    <tr>
                                        <td><input type="checkbox" value=""></td>
                                        <td><img src="img/moon_roof.jpg" /></td>
                                        <td>Moonroof with Universal Garage Door Opener <span class="price">+ $356</span></td>
                                        <td>Cum sociis natoque penatibus et magnis dis parturient. Vimus magna, accumsan a tortor et porttitor. Donec luctus hendrerit aliquam.ccumsan placerat nisl ac rutrum. Quisque ac egestas nisi. Etiam sed consequat dolor. In ultrices purus placerat massa</td>
                          
                                    </tr>
                                    <tr>
                                        <td><input type="checkbox" value=""></td>
                                        <td><img src="img/side_mirror.jpg" /></td>
                                        <td>Cross Traffic Alert System <span class="price">+ $356</span></td>
                                        <td> Vimus magna, accumsan a tortor et porttitor. Donec luctus hendrerit aliquam.ccumsan placerat niCum sociis natoque penatibus et magnis dis parturient.sl ac rutrum. Quisque ac egestas nisi. Etiam sed consequat dolor. In ultrices purus placerat massa</td>
                                      
                                    </tr>
                                    <tr>
                                        <td><input type="checkbox" value=""></td>
                                        <td><img src="img/moon_roof.jpg" /></td>
                                        <td>Moonroof with Universal Garage Door Opener <span class="price">+ $356</span></td>
                                        <td>Cum sociis natoque penatibus et magnis dis parturient. Vimus magna, accumsan a tortor et porttitor. Donec luctus hendrerit aliquam.ccumsan placerat nisl ac rutrum. Quisque ac egestas nisi. Etiam sed consequat dolor. In ultrices purus placerat massa</td>
                                    </tr>
                                </tbody>
                            </table>

                            
                           
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                Wheels
                            </a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Check me out
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<script type="text/x-handlebars-template" id="transmission-template">
	<option>{{trim}} {{transmission.transmissionType}}</option>
</script>
<script type="text/x-handlebars-template" id="car-year-template">
	<option>{{year.year}}</option>
</script>
