<header>
        <div class="navbar navbar-fixed-top head-wrap" role="navigation">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="/img/dealer_sell_me_an_auto_logo.fw.png" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <form class="navbar-form navbar-right" role="form">
                    <span class="contacts">
                        Invitation
                    </span>
                    <div class="btn-group login-info">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                            <span class="profile-pic"><img src="/user-image/" /></span><?php echo $this->user_profiles['fname']; ?> <?php echo $this->user_profiles['lname']; ?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Edit My Profile</a></li>
                            <li><a href="#">Bids</a></li>
                            <li><a href="#">Account Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="/user/logout"><strong>Log Out</strong></a></li>
                        </ul>
                    </div>
                </form>
            </div><!--/.navbar-collapse -->



        </div>
    </header>