<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <?php
	echo $this->partial("elements/includes.phtml");
	echo $this -> headTitle();
	echo $this -> headLink();
	?>

</head>
<body class="dash-wrapper">
    <?php
		echo $this->partial("elements/user/dealer-header.phtml", array("user_profiles"=>$this->user_profiles, "user_image"=>$this->user_image )  );
	?>
    <div class="page-container">

        <div class="page-sidebar ul-menu">
            <ul>
                <li><a href="/user/"><i class="icon-dash"></i><i class="home"></i>Dashboard</a></li>
                <li><a href="/user/dashboard/"><i class="icon-l-post"></i>Latest Post</a></li>
                <li><a href="/bids/"><i class="icon-bids"></i>Bids</a></li>
                <li><a href="/notifications/"><i class="icon-preferences"></i>Notifications</a></li>
                <li><a href="/user/"><i class="icon-settings"></i>Settings</a></li>
            </ul>
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
            	<div class="row">
                    <div class="container" style=" width:100% !important;">
                        <div class="white-wrap my-account">
                        	<div class="row">
								<?php echo $this->layout()->content?>
                            </div>
                        </div>
                    </div>
                </div>            
            </div>
        </div>
    </div>
    <?php
		echo $this->partial("elements/footer.phtml");
	?>
	<?php echo $this -> headScript();?>
</body>
</html>
