<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php
		echo $this->partial("elements/includes.phtml")
		?>
		
		<?php
		echo $this -> headTitle();
		echo $this -> headLink();
		
		?>
	</head>
	<body>
    	<input type="text" name="build" id="build" value="<?php echo $this->build;?>">
		<?php
		echo $this->partial("elements/header.phtml", array("user_profiles"=>$this->user_profiles, "register_page"=>$this->register_page, "hide_wrapper"=>false)  );
		echo $this->partial("elements/select_a_brand.phtml", array("years"=>$this->years));
		echo $this->partial("elements/login.phtml");
		?>
		<!--Main Body starts-->
		<div class="mainBody">
			<?php //echo $this->partial("elements/left.phtml"); ?>
			<!--Main starts-->
			<div id="main">
				<?php echo $this->layout()->content?>
			</div>
			
			<div class="clear"></div>
		</div>
		<?php
			//echo $this->partial("elements/right.phtml");
			echo $this->partial("elements/footer.phtml");
		?>
		<?php echo $this -> headScript();?>

	</body>


</html>