<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php
		echo $this->partial("elements/includes.phtml")
		?>
		
		<?php
		echo $this->headTitle();
		echo $this->headLink();
		
		?>
	</head>
	<body>
		<?php
		echo $this->partial("elements/header.phtml", array("register_page"=>true, "hide_wrapper"=>true))
		?>
		<!--Main Body starts-->
		<div class="mainBody">
			<?php //echo $this->partial("elements/left.phtml"); ?>
			<!--Main starts-->
			<div id="main">
				<?php echo $this->layout()->content?>
			</div>
			
			<div class="clear"></div>
		</div>
		<?php
			//echo $this->partial("elements/right.phtml");
			echo $this->partial("elements/footer.phtml");
		?>
		<?php echo $this -> headScript();?>
		
	</body>
    
</html>