<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    
    <?php
	echo $this->partial("elements/includes.phtml");
	echo $this -> headTitle();
	echo $this -> headLink();
	?>

</head>
<body>
    <?php
		echo $this->partial("elements/user/header.phtml", array("user_profiles"=>$this->user_profiles, "user_image"=>$this->user_image )  );
	?>
    <br clear="all">
    <div class="white-wrap page-container">
    	<div class="page-sidebar">
        
            <div class="panel panel-default">
              <div class="panel-heading">My Account</div>
              <div class="panel-body panel-user-details <?php echo $this->account_active;?>">
                <img src="/user-image/" /> <span><?php echo $this->user_profiles['fname']; ?> <?php echo $this->user_profiles['lname']; ?></span><br><?php echo $this->user_profiles['city_town']; ?>, <?php echo $this->user_profiles['state_province']; ?>
                
                <br clear="all">
                <p><a href="/user/">Edit Profile</a></p>
              </div>
            
              <!-- List group -->
              <ul class="list-group">
                <li class="list-group-item <?php echo $this->posted_active;?>" ><a href="/user/posted"><img src="/public/img/posted-icon.fw.png" border="0" > Posted</a></li>
                <li class="list-group-item"><a href="/user/"><img src="/public/img/account-settings-icon.fw.png" border="0" > Account Settings</a></li>
              </ul>
            </div>
            
            
            
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
            	<div class="row">
                    <div class="container" style=" width:100% !important;">
                        <div class="my-account">
                        	<div class="row">
								<?php echo $this->layout()->content?>
                            </div>
                        </div>
                    </div>
                </div>            
            </div>
        </div>
       <br clear="all">
    </div>
    
    
    
    <?php
		echo $this->partial("elements/footer.phtml");
	?>
	<?php echo $this -> headScript();?>
</body>
</html>
