<div class="form-group">
    <label for="Confirmpassword" class="col-sm-4 control-label">Car Makes</label>
    <div class="col-sm-8">
        <select  name="car_make_selection" id="car_make_selection">
        	<option value="">Please Select</option>
            <?php 
                foreach($this->car_makes as $car) {
                    echo "<option value=".$car['id'].">".$car['name']."</option>";
                }
            ?>
        </select> <a href="#" class="btn" id="car_select_button">Add</a>
    </div>
</div>

<div class="form-group">
	<label for="Confirmpassword" class="col-sm-4 control-label">Selected</label>
    <div class="col-sm-8">
    	<div id="selected_car"></div>
    </div>
</div>