<div class="container" style="padding-top: 100px;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Create an Account</h3>
                            <ul id="myTab" class="nav nav-tabs">
                                <li class="active"><a href="#"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 1 </span> My Account</a></li>
                                <li class=""><a href="/register/step2"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 2 </span>Personal Information</a></li>
                                <li class=""><a href="/register/step3"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 3 </span>Contact Information</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div class="tab-pane fade in" id="contactinfo">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <form class="form-horizontal" role="form">
                                                <p class="s-title">Contacts</p>
                                                <div class="form-group">
                                                    <label for="Cellphone" class="col-sm-4 control-label">Cell Phone</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="Cellphone" placeholder="#">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="Telephone" class="col-sm-4 control-label">Telephone</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="Telephone" placeholder="#">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="Fax" class="col-sm-4 control-label">Fax</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="Fax" placeholder="#">
                                                    </div>
                                                </div>
                                                <p class="s-title">Address</p>
                                                <div class="form-group">
                                                    <label for="Street" class="col-sm-4 control-label">Street</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="Street" placeholder="Street">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="City" class="col-sm-4 control-label">City/Town</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="City" placeholder="City/Town">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="State" class="col-sm-4 control-label">State/Province</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="State" placeholder="State/Province">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="Zip" class="col-sm-4 control-label">ZIP Code</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="Zip" placeholder="ZIP Code">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-sm-offset-4 col-sm-8">
                                                        <a href="#personalinfo" data-toggle="tab" class="btn btn-success">Next</a>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="personalinfo">
                                    <div class="col-md-6">
                                        <form class="form-horizontal" role="form">
                                            <p class="s-title">Basic Info</p>
                                            <div class="form-group">
                                                <label for="Firstname" class="col-sm-4 control-label">First Name</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="Firstname" placeholder="Firstname">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="Lastname" class="col-sm-4 control-label">Last Name</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="Lastname" placeholder="Lastname">
                                                </div>
                                            </div>
                                            <p class="s-title">About Me</p>
                                            <div class="form-group">
                                                <label for="aboutyourself" class="col-sm-4 control-label">Tell us a bit yourself</label>
                                                <div class="col-sm-8">
                                                    <textarea class="form-control" id="aboutyourself" rows="10"></textarea>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="s-title">Profile Picture</p>
                                        <form class="form-horizontal" role="form">
                                            <img src="..." alt="..." class="col-sm-3 img-thumbnail">
                                            <div class="form-group">
                                                <label for="exampleInputFile">File input</label>
                                                <input type="file" id="exampleInputFile">
                                                <p class="help-block">Example block-level help text here.</p>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                                <div class="tab-pane fade active in" id="account">
                                    <div class="col-md-6">
                                        <form class="form-horizontal" role="form">
                                            <p class="s-title">Account Security</p>
                                            <div class="form-group">
                                                <label for="email" class="col-sm-4 control-label">Email Address</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="Firstname" placeholder="emailaddress">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="password" class="col-sm-4 control-label">Password</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="Newpassword" placeholder="New Password">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="Confirmpassword" class="col-sm-4 control-label">Confirm Password</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="Confirmnewpassword" placeholder="Confirm New Password">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-4 col-sm-8">
                                                    <a href="#contactinfo" data-toggle="tab" class="btn btn-success">Next</a>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>