<div class="container" style="padding-top: 100px;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Create an Account</h3>
                            <ul id="myTab" class="nav nav-tabs">
                                <li class=""><a href="/register/step1"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 1 </span> My Account</a></li>
                                <li class="active"><a href="#"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 2 </span>Personal Information</a></li>
                                <li class=""><a href="/register/step3"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 3 </span>Contact Information</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                            	<div class="tab-pane fade active in" id="personalinfo">
                                    <div class="col-md-6">
                                        <form id="form_step2" name="form_step2" class="form-horizontal" role="form" method="post">
                                            <p class="s-title">Basic Info</p>
                                            <div class="form-group">
                                                <label for="Firstname" class="col-sm-4 control-label">First Name</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="fname" name="fname" placeholder="Firstname" value="<?php echo $this->temp_registration['fname'];?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="Lastname" class="col-sm-4 control-label">Last Name</label>
                                                <div class="col-sm-8">
                                                    <input type="text" class="form-control" id="lname" name="lname" placeholder="Lastname" value="<?php echo $this->temp_registration['lname'];?>">
                                                </div>
                                            </div>
                                            <p class="s-title">About Me</p>
                                            <div class="form-group">
                                                <label for="aboutyourself" class="col-sm-4 control-label">Tell us a bit yourself</label>
                                                <div class="col-sm-8">
                                                    <textarea class="form-control" id="about_user" name="about_user" rows="10"><?php echo $this->temp_registration['about_user'];?></textarea>
                                                </div>
                                            </div>
                                            <div class="col-sm-offset-4 col-sm-8">
                                                <button class="btn btn-success">Next</button>
                                            </div>

                                        </form>
                                    </div>
                                    <!--
                                    <div class="col-md-6">
                                        <p class="s-title">Profile Picture</p>
                                        <form class="form-horizontal" role="form">
                                            <img src="..." alt="..." class="col-sm-3 img-thumbnail">
                                            <div class="form-group">
                                                <label for="exampleInputFile">File input</label>
                                                <input type="file" id="exampleInputFile">
                                                <p class="help-block">Example block-level help text here.</p>
                                            </div>
                                        </form>
                                    </div>
                                    -->
                                </div>
                            </div>
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>