<div class="container" style="padding-top: 100px;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Create an Account</h3>
                            <ul id="myTab" class="nav nav-tabs">
                                <li class=""><a href="/register/step1?type=<?php echo $this->user_type; ?>"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 1 </span> My Account</a></li>
                                <li class=""><a href="/register/step2?type=<?php echo $this->user_type; ?>"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 2 </span>Personal Information</a></li>
                                <li class="active"><a href="#"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 3 </span>Contact Information</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                            	<div class="tab-pane fade active in" id="contactinfo">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <form id="form_step3" class="form-horizontal" role="form">
                                                <p class="s-title">Contacts</p>
                                                <div class="form-group">
                                                    <label for="Cellphone" class="col-sm-4 control-label">Cell Phone</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="cell_no" name="cell_no" placeholder="#">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="Telephone" class="col-sm-4 control-label">Telephone</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="tell_no" name="tell_no" placeholder="#">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="Fax" class="col-sm-4 control-label">Fax</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="fax_no" name="fax_no" placeholder="#">
                                                    </div>
                                                </div>
                                                <p class="s-title">Address</p>
                                                <div class="form-group">
                                                    <label for="Street" class="col-sm-4 control-label">Street</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="street" name="street" placeholder="Street">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="City" class="col-sm-4 control-label">City/Town</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="city_town" name="city_town" placeholder="City/Town">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="State" class="col-sm-4 control-label">State/Province</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="state_province" name="state_province" placeholder="State/Province">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="Zip" class="col-sm-4 control-label">ZIP Code</label>
                                                    <div class="col-sm-8">
                                                        <input type="text" class="form-control" id="zip_code" name="zip_code" placeholder="ZIP Code">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-sm-offset-4 col-sm-8">
                                                        <button class="btn btn-success">Next</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>