<div class="container" style="padding-top: 100px;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Create an Account</h3>
                           

                            
                            <ul id="myTab" class="nav nav-tabs">
                                <li class="active"><a href="#"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 1 </span> My Account</a></li>
                                <li class=""><a href="/register/step2"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 2 </span>Personal Information</a></li>
                                <li class=""><a href="/register/step3"><span style="font-weight: bold; font-size: 18px; color: #7DB136;">Step 3 </span>Contact Information</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                            	<div class="tab-pane fade active in" id="account">
                                    <div class="col-md-6">
                                        <form id="form_step1" class="form-horizontal" role="form" method="post">
                                         	<input type="hidden" name="type" id="type" value="<?php echo $this->user_type; ?>" />
                                            
                                            
                                            <p class="s-title">Account Security</p>
                                            <div class="form-group">
                                                <label for="email" class="col-sm-4 control-label">Email Address</label>
                                                <div class="col-sm-8">
                                                    <input type="email" class="form-control" id="email" name="email" placeholder="Email Address" <?php echo $this->disabled;?> value="<?php echo $this->temp_registration['email'];?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="password" class="col-sm-4 control-label">Password</label>
                                                <div class="col-sm-8">
                                                    <input type="password" class="form-control" id="password" name="password" value="" <?php echo $this->disabled;?> >
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="Confirmpassword" class="col-sm-4 control-label">Confirm Password</label>
                                                <div class="col-sm-8">
                                                    <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" value="" <?php echo $this->disabled;?>  >
                                                </div>
                                            </div>
                                            <?php
                                            if($this->user_type == "dealer"){
												echo $this->partial("register/car_makes.phtml", array("user_type"=>$this->user_type, "car_makes"=>$this->car_makes )  );
											}
											?>
                                            
                                            <div class="form-group">
                                                <div class="col-sm-offset-4 col-sm-8">
                                                    <button class="btn btn-success" <?php echo $this->disabled;?>>Next</button>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>