<div class="container" style="padding-top: 100px;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Thank you for registering !</h3>
                           
                            <p>Hi <strong><?php echo sprintf('%s %s' , $this->temp_registration['fname'], $this->temp_registration['lname']);?></strong> an email confirmation has been sent to <strong><em><?php echo $this->temp_registration['email']; ?></em></strong>. Please activate your account to continue. </p>
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>