
    <!--
    <div class="modal fade" id="Signup" tabindex="-1" role="dialog" aria-labelledby="Signup" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div style="background-color: #0E4C75; padding: 20px;">
                        <h3 style="color: #fff; text-align: center; margin:0px;">Let's get started, Choose an Option</h3>
                    </div>

                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6" style="text-align: center;">
                            <h3 style="margin: 0px 0 30px 0;">I am a <span style="color:#FFA54C;">Dealer</span></h3>
                            <div style="border: 1px dashed #FFA54C; padding: 20px; border-radius: 3px; ">
                                <p>Create a <span style="color:red; font-weight:bold;">Free profile</span> - Search vehicles customers are ready to buy, and out price your competitors.</p>
                                <a class="btn btn-warning" y>Create an Account</a>
                            </div>
                        </div>
                        <div class="col-sm-6" style="text-align: center;">
                            <h3 style="margin:0px 0 30px 0;">I am a <span style="color: #92BC48;">User</span></h3>
                            <div style="border: 1px dashed #92BC48; padding: 20px; border-radius: 3px;">
                                <p><span style="color: red; font-weight: bold;">It's FREE</span> - Build your own car and get the lowest price from our networked.. </p>
                                <a class="btn btn-success">Create an Account</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    -->
    
    <div class="modal fade" id="ZIPcode" tabindex="-1" role="dialog" aria-labelledby="ZIPcode" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <form class="form-horizontal" role="form" id="enter-zip-form">
                        <div class="form-group">
                            <div class="col-sm-8">
                                <label class="control-label" style="color: #0D4B72; font-size: 16px; padding-top: 0px;">NOW ENTER YOUR ZIP CODE:</label>
                                <span style="font-size: 12px; display: block;">ZIP code is used to find dealers near you.</span>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control input-lg" id="inputZZIPcode" placeholder="">
                            </div>
                        </div>
                    </form>
                    <div style="display: block; margin: 20px auto 0; text-align: center;">
                        <a class="btn btn-warning btn-lg btn-shadow enter-zip-code" style="text-align: left; font-weight: bold; padding: 10px 25px;"><span style="display: block; color: #333333; font-size: 13px; font-weight: normal;">Proceed to</span> MODEL</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    


<script type="text/x-handlebars-template" id="loaded-model-template">
	<li><a href="#" class="select-car-model" data-target="#ZIPcode" data-dismiss="modal" data-id="{{niceName}}"><img src="img/genesis_car.png" id="model_{{id}}"/> <span>{{name}}</span></a></li>
</script>
