<div class="container" style="padding-top: 100px;">
    <div class="account-container">
        <div class="row">
            <div class="white-wrap my-account">
                <div class="row">
                    <div class="col-md-12">
                        <h3>Forgot Password</h3>
                        <form name="form" id="form_forgot_password" method="post">
	                        <p>Plese type the email address that you used in registration.<br />
                            <input type="email" name="email" id="email" class="form-control" style="width:250px;" placeHolder="Email Address" /><br />
 <button class="btn btn-primary">Send</button>
							</p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>