<input type="hidden" name="make" id="make-value" value="<?php echo $this->makeName?>"/>
<input type="hidden" name="model" id="model-value" value="<?php echo $this->modelName?>"/>
<input type="hidden" name="year" id="year-value" value="<?php echo $this->year?>"/>


<h1 class="select-car-header">Select your Car</h1>
<div class="row" id="select-car-list">
	
</div>


<script type="text/x-handlebars-template" id="car-style-template">
	<div class="col-lg-3 col-md-3 col-xs-6">
		<div class="row">
			<div class="col-lg-11 col-md-11 col-xs-11 car-style">
				<div class="row submodel-container">
					<h2 class="submodel-name">{{submodel.modelName}}</h2>
				</div>
				<div class="row pic-cont">
					<img src="/public/img/select-car-icon.jpg" alt="{{submodel.modelName}}" id="img_{{id}}" class="pic"/>
				</div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-xs-12">
						<div class="row">
							<label class="col-lg-12 col-md-12 col-xs-12 submodel-variant-name">{{name}}</label>
						</div>
						<div class="row">
							<label class="col-lg-8 col-md-8 col-xs-8 label-detail">Starting MS Price</label>
							<span class="col-lg-4 col-md-4 col-xs-4 value-detail"><strong>10000</strong></span>
						</div>
						<div class="row">
							<label class="col-lg-8 col-md-8 col-xs-8 label-detail">EPA Est. MPG City/Hwy</label>
							<span class="col-lg-4 col-md-4 col-xs-4 value-detail"><strong>28/36</strong></span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-xs-12">
						<div class="row">
							<button class="exterior-config col-lg-10 col-md-10 col-xs-10" data-id="{{id}}">
								<div class="row exterior-button-wrap">
									<div class="col-lg-12 col-xs-12 col-md-12">
										<span class="proceed-to">Proceed To</span><br/>
										<strong class="exterior-bold">Exterior</strong>
									</div>
									<div class="arrow-icon"></div>
								</div>
							</button>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
	</div>
</script>
