<div class="container" style="padding-top: 100px; width:40%;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="modal-title" style="font-family: 'Open Sans'; font-weight: 300;">Login to your Account</h3>
                           
                            <div>
                                <input type="text" placeholder="Email Address" class="form-control"><br />
                                <input type="text" placeholder="Password" class="form-control"><br />
                                <button style="float: right;" class="btn btn-success signin_btn">Sign In</button>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>