<div style="font-family:Verdana, Geneva, sans-serif; font-size:12px;">
<h1>Sellmeanauto Account</h1>
<h3>Retrieved Password</h3>
<p>Hi <?php echo $this->user_profiles['fname']; ?> <?php echo $this->user_profiles['lname']; ?>,</p>
<p>We have automatically updated your password and we strongly recommend to update your password in your profile page.</p>
<p>Temporary Password : <strong><?php echo $this->ran;?></strong></p>
</div>