<div class="col-md-12">
    <h3 class="consumer_hdr">Account Settings</h3>
	<div class="col-md-8">
        <form id="form_credentials" class="form-horizontal" role="form" method="post">
                <p class="s-title">Account Security</p>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-3 control-label">Your Email Address</label>
                    <div class="col-sm-8">
                        <p style="margin-top: 8px; font-style: italic;"><?php echo $this->user_profiles['email']; ?></p>
                    </div>
                </div>
                <div class="form-group">
                    <label for="Currentpassword" class="col-sm-3 control-label">Current Password</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="currentpassword" name="currentpassword" placeholder="Currentpassword">
                    </div>
                </div>
                <div class="form-group">
                    <label for="Newpassword" class="col-sm-3 control-label">New Password</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="newpassword" name="newpassword" placeholder="New Password">
                    </div>
                </div>
                <div class="form-group">
                    <label for="Confirmnewpassword" class="col-sm-3 control-label">Confirm New Password</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="confirmnewpassword" name="confirmnewpassword" placeholder="Confirm New Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button class="btn btn-success">Save</button>
                    </div>
                </div>

            </form>
        
    </div>
</div>