<div class="col-md-12">
    <h3 class="consumer_hdr">Edit My Profile</h3>
	<div class="col-md-8">
    				<p class="s-title">Profile Picture</p>
                    <form name="form_img" id="form_img" method="post" enctype="multipart/form-data" action="/user/">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label">&nbsp;</label>
                            <div class="col-sm-8">
                                <img src="/user-image/" class="img-thumbnail profile-img" >
                                <input type="file" name="file_upload" id="file_upload" >
                                <p class="muted"><small><?php echo $this->error_msg;?></small></p>
                                <small class="muted">By uploading a file you certify that you have the right distribute
this picture and that it does not violate the Terms and Service.</small>
                            </div>
                        </div>
					</form>	
                     <br clear="all" />
                     <br clear="all" />  
                	<form id="form_personal_info" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                    	
                        	
                        <p class="s-title">Basic Info</p>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label">Your Email Address</label>
                            <div class="col-sm-8">
                                <p style="margin-top: 8px; font-style: italic;"><?php echo $this->user_profiles['email']; ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Firstname" class="col-sm-4 control-label">First Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="fname" name="fname" placeholder="Firstname" value="<?php echo $this->user_profiles['fname']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Lastname" class="col-sm-4 control-label">Last Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="lname" name="lname" placeholder="Lastname" value="<?php echo $this->user_profiles['lname']; ?>">
                            </div>
                        </div>
                        <p class="s-title">Contacts</p>
                        <div class="form-group">
                            <label for="Cellphone" class="col-sm-4 control-label">Cell Phone</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="cell_no" name="cell_no" placeholder="#" value="<?php echo $this->user_profiles['cell_no']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Telephone" class="col-sm-4 control-label">Telephone</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="tell_no" name="tell_no" placeholder="#" value="<?php echo $this->user_profiles['tell_no']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Fax" class="col-sm-4 control-label">Fax</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="fax_no" name="fax_no" placeholder="#" value="<?php echo $this->user_profiles['fax_no']; ?>">
                            </div>
                        </div>
                        <p class="s-title">Address</p>
                        <div class="form-group">
                            <label for="Street" class="col-sm-4 control-label">Street</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="street" name="street" placeholder="Street" value="<?php echo $this->user_profiles['street']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="City" class="col-sm-4 control-label">City/Town</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="city_town" name="city_town" placeholder="City/Town" value="<?php echo $this->user_profiles['city_town']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="State" class="col-sm-4 control-label">State/Province</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="state_province" name="state_province" placeholder="State/Province" value="<?php echo $this->user_profiles['state_province']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Zip" class="col-sm-4 control-label">ZIP Code</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="zip_code" name="zip_code" placeholder="ZIP Code" value="<?php echo $this->user_profiles['zip_code']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-8">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
					</form>
                </div>
</div>