<div class="car-list dealer-car-list" >
    <table id="dahsboard_tb" class="table table-striped">
        <thead style="background-color: #808080; color: #fff;">
            <tr>
                <th class="col-md-2">Item</th>
                <th class="col-md-4">Details</th>
                <th class="col-md-2">Starting Price</th>
                <th class="col-md-2">Bids</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>


<script type="text/x-handlebars-template" id="dealer-dashboard-list-template">
	<tr>
		<td valign="top">
			<img id="car_main_image_{{order_id}}" />
			<!--
			{{order_id}}<br />
			{{order_date}}<br />
			{{style_id}}<br />
			{{zipcode}}<br />
			{{status}}<br />
			{{date_diff}}<br />
			{{duration}}
			-->
		</td>
		<td valign="top">
			<h4 id="car_name_{{order_id}}">-</h4>
			<p>Engine: <span id="engine_{{order_id}}">-</span></p>
			<p>Transmission: <span id="transmission_{{order_id}}">-</span></p>
			<p>Exterior Color: <span id="exterior_color_{{order_id}}">-</span></p>
			<p>Interior Color: <span id="interior_color_{{order_id}}">-</span></p>
			<a href="/user/order/{{order_id}}" class="btn btn-default">View Details</a>
		</td>
		<td valign="top"><p id="total_baseInvoice_{{order_id}}" class="con-bid">$0</p></td>
		<td valign="top">
			<p class="c-bid">$0<span>0 Bids</span></p>
			<p class="ends">0d left</p>
			<a href="/user/order/{{order_id}}" class="btn btn-warning btn-lg">Place a Bid</a>
		</td>
	</tr>
</script>

<script type="text/x-handlebars-template" id="exterior-options-template">
	<li style="margin-top:10px;">{{name}} <span class="price" style="float:right; margin-right:20px;">+ ${{price.baseMSRP}}</span></li>
</script>

<script type="text/x-handlebars-template" id="interior-options-template">
	<li style="margin-top:10px;">{{name}} <span class="price" style="float:right; margin-right:20px;">+ ${{price.baseMSRP}}</span></li>
</script>
