<div class="car-list">
    <table id="dahsboard_tb" class="table table-striped">
        <thead style="background-color: #808080; color: #fff;">
            <tr>
                <th class="col-md-2">Item</th>
                <th class="col-md-4">Details</th>
                <th class="col-md-2">Configured Price</th>
                <th class="col-md-2">Current Bid</th>
                <th class="col-md-1">Ending</th>
                <th class="col-md-1">Action</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>


<script type="text/x-handlebars-template" id="dashboard-list-template">
	<tr>
		<td>
			{{order_id}}<br />
			{{order_date}}
		</td>
		<td>
			<h4 id="car_name_{{order_id}}">-</h4>
			<p>Engine: <span id="engine_{{order_id}}">-</span></p>
			<p>Transmission: <span id="transmission_{{order_id}}">-</span></p>
			<p>Exterior Color: <span id="exterior_color_{{order_id}}">-</span></p>
			<p>Interior Color: <span id="interior_color_id">-</span></p>
			<button type="submit" class="btn btn-primary">View Details</button>
		</td>
		<td><p class="con-bid">$0</p></td>
		<td><p class="c-bid">$0<span>0 Bids</span></p></td>
		<td><p class="ends">0d left</p></td>
		<td><button type="submit" class="btn btn-warning btn-lg">Place a Bid</button></td>
	</tr>
</script>
