<div class="col-md-12">
    <h3>My Account</h3>
    <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="#personalinformation" data-toggle="tab">Personal Information</a></li>
        <li class=""><a href="#account" data-toggle="tab">Account</a></li>
        <li class=""><a href="#credentials" data-toggle="tab">Password</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="personalinformation">
            <div class="row">
	            
                <div class="col-md-6">
                	<form id="form_personal_info" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                        <p class="s-title">Basic Info</p>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-4 control-label">Your Email Address</label>
                            <div class="col-sm-8">
                                <p style="margin-top: 8px; font-style: italic;"><?php echo $this->user_profiles['email']; ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Firstname" class="col-sm-4 control-label">First Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="fname" name="fname" placeholder="Firstname" value="<?php echo $this->user_profiles['fname']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Lastname" class="col-sm-4 control-label">Last Name</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="lname" name="lname" placeholder="Lastname" value="<?php echo $this->user_profiles['lname']; ?>">
                            </div>
                        </div>
                        <p class="s-title">Contacts</p>
                        <div class="form-group">
                            <label for="Cellphone" class="col-sm-4 control-label">Cell Phone</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="cell_no" name="cell_no" placeholder="#" value="<?php echo $this->user_profiles['cell_no']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Telephone" class="col-sm-4 control-label">Telephone</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="tell_no" name="tell_no" placeholder="#" value="<?php echo $this->user_profiles['tell_no']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Fax" class="col-sm-4 control-label">Fax</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="fax_no" name="fax_no" placeholder="#" value="<?php echo $this->user_profiles['fax_no']; ?>">
                            </div>
                        </div>
                        <p class="s-title">Address</p>
                        <div class="form-group">
                            <label for="Street" class="col-sm-4 control-label">Street</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="street" name="street" placeholder="Street" value="<?php echo $this->user_profiles['street']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="City" class="col-sm-4 control-label">City/Town</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="city_town" name="city_town" placeholder="City/Town" value="<?php echo $this->user_profiles['city_town']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="State" class="col-sm-4 control-label">State/Province</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="state_province" name="state_province" placeholder="State/Province" value="<?php echo $this->user_profiles['state_province']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Zip" class="col-sm-4 control-label">ZIP Code</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="zip_code" name="zip_code" placeholder="ZIP Code" value="<?php echo $this->user_profiles['zip_code']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-8">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
					</form>
                </div>
                <div class="col-md-6">
                    <p class="s-title">Profile Picture</p>
                    	<form name="form_img" id="form_img" method="post" enctype="multipart/form-data" action="/user/">
                        	
                            <img src="/user-image/" class="col-sm-3 img-thumbnail" style="margin-right:10px;">
                            <div>
                                <input type="file" name="file_upload" id="file_upload" >
                                <p class="muted"><small><?php echo $this->error_msg;?></small></p>
                            </div>
                        </form>
                </div>
               
            </div>
        </div>
        <div class="tab-pane fade" id="account">
            <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
        </div>
        <div class="tab-pane fade" id="credentials">
            <form id="form_credentials" class="form-horizontal" role="form" method="post">
                <p class="s-title">Account Security</p>
                <div class="form-group">
                    <label for="Currentpassword" class="col-sm-3 control-label">Current Password</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="currentpassword" name="currentpassword" placeholder="Currentpassword">
                    </div>
                </div>
                <div class="form-group">
                    <label for="Newpassword" class="col-sm-3 control-label">New Password</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="newpassword" name="newpassword" placeholder="New Password">
                    </div>
                </div>
                <div class="form-group">
                    <label for="Confirmnewpassword" class="col-sm-3 control-label">Confirm New Password</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="confirmnewpassword" name="confirmnewpassword" placeholder="Confirm New Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button class="btn btn-success">Save</button>
                    </div>
                </div>

            </form>
        </div>

    </div>
</div>