<div class="container" style="padding-top: 100px;">
        <div class="account-container">
            <div class="row">
                <div class="white-wrap my-account">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Personal Information</h3>
                            
                            <p>This is a profile page for user <strong><?php echo $this->user_profiles['fname']; ?> <?php echo $this->user_profiles['lname']; ?></strong></p>
                            <p> <span class="glyphicon glyphicon-log-out"></span> <a href="/user/logout">Logout</a> </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>