<input type="hidden" name="user_page" id="user_page" value="order"/>
<input type="hidden" name="order_id" id="order_id" value="<?php echo $this->order_id;?>"/>
<input type="hidden" name="style_id" id="style_id" />
<div class="dis-over">
    <div class="row">
        <div class="col-md-6">
            <div id="car-main-image-<?php echo $this->order_id;?>"><img src="/public/img/ajax-loader.gif" /></div>
            <div class="d-info">
                <ul>

                    <li class="icon-mpg">

                        <h5>EPA Est. MPG</h5>
                        <p id="mpg_<?php echo $this->order_id;?>">-<span>City/Hwy</span></p>
                    </li>
                    <li class="icon-hp">
                        <h5>Horsepower</h5>
                        <p id="horsepower_<?php echo $this->order_id;?>">-</p>
                    </li>
                    <li class="icon-seat">
                        <h5>Seating</h5>
                        <p id="numOfSeats_<?php echo $this->order_id;?>">-</p>
                    </li>
                </ul>


            </div>
            <div class="sp-details">
                <h4>Standard Package</h4>
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active"><a href="#engine" data-toggle="tab">Engine</a></li>
                    <li><a href="#transmission" data-toggle="tab">Transmission</a></li>
                    <li><a href="#steering" data-toggle="tab">Steering</a></li>
                    <li><a href="#chasis" data-toggle="tab">Chasis</a></li>
                    <li><a href="#dimensions" data-toggle="tab">Dimensions</a></li>
                </ul>

                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade active in additional-selections" id="engine">
                        <table id="engine-options-<?php echo $this->order_id;?>" class="table table-striped table-condensed">
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade additional-selections" id="transmission">
                        <table id="transmission-options-<?php echo $this->order_id;?>" class="table table-striped table-condensed">
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade additional-selections" id="steering">
                        <table id="steering-options-<?php echo $this->order_id;?>" class="table table-striped table-condensed">
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade additional-selections" id="chasis">
                        <table id="chasis-options-<?php echo $this->order_id;?>" class="table table-striped table-condensed">
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade additional-selections" id="dimensions">
                        <table id="dimensions-options-<?php echo $this->order_id;?>" class="table table-striped table-condensed">
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12 c-info">
                    <h5>Client Information</h5>
                    <div class="row">
                        <div class="col-md-3">
                            <h5><strong id="zipcode">-</strong></h5>
                            <p>ZIP CODE</p>
                        </div>
                        <div class="col-md-8">
                            <h5 id="address">-</h5>
                            <p>Address</p>
                        </div>
                    </div>
                    <h3 id="car_name_<?php echo $this->order_id;?>">-</h3>
                    <h5 id="transmission_<?php echo $this->order_id;?>"></h5>
                    <br clear="all" />
                    <div class="row">
                        <div class="col-md-4">
                            <p>Exterior Color: <span id="exterior_color_<?php echo $this->order_id;?>">-</span></p>

                        </div>
                        <div class="col-md-8">
                            <p>Interior Color: <span id="interior_color_<?php echo $this->order_id;?>">-</span></p>
                        </div>
                    </div>
                    <div class="white-wrap b-price-dis">
                        <form class="form-horizontal" role="form">
                            <div class="form-group">
                                <label class="col-sm-4 control-label" style="text-align:left;">Price</label>
                                <div class="col-sm-8">
                                    <p id="total_baseInvoice_<?php echo $this->order_id;?>">$0</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label" style="text-align:left;">Current Bid</label>
                                <div class="col-sm-8">
                                    <p id="current_bid" class="c-bid">$0 <span>0 Bids</span></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label" style="text-align:left;">FINANCE ESTIMATE</label>
                                <div class="col-sm-8">
                                    <p id="finance_estimate">$0 <span>per month for 72 months</span></p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">

                                    <a class="btn btn-warning btn-lg place-bid" data-order_id="<?php echo $this->order_id;?>">Place a Bid</a>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="">
                        <h5>Your Additional Selections</h5>
                        <div class="panel-group" id="accordion">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel1"> Exterior</a>
                                    </h4>
                                </div>
                                <div id="panel1" class="panel-collapse collapse in">
                                    <div class="panel-body additional-selections">
                                        <ol id="exterior-options_<?php echo $this->order_id;?>"></ol>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel2"> Interror</a>
                                    </h4>
                                </div>
                                <div id="panel2" class="panel-collapse collapse">
                                    <div class="panel-body additional-selections">
                                        <ol id="interior-options_<?php echo $this->order_id;?>"></ol>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel3"> Accessories</a>
                                    </h4>
                                </div>
                                <div id="panel3" class="panel-collapse collapse">
                                    <div class="panel-body additional-selections">
                                        <ol id="accessories-options_<?php echo $this->order_id;?>"></ol>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                        
<?php echo $this->partial("elements/user/place-bid-modal.phtml"); ?>
                        
<script type="text/x-handlebars-template" id="exterior-options-template">
	<li style="margin-top:10px;">{{name}} <span class="price" style="float:right; margin-right:20px;">+ ${{price.baseMSRP}}</span></li>
</script>

<script type="text/x-handlebars-template" id="interior-options-template">
	<li style="margin-top:10px;">{{name}} <span class="price" style="float:right; margin-right:20px;">+ ${{price.baseMSRP}}</span></li>
</script>

<script type="text/x-handlebars-template" id="accessories-options-template">
{{#each equipment}}	
	<li>{{this.name}}
		<ul>
			{{#each attributes}}	
				<li>{{this.name}} : {{this.value}}</li>
			{{/each}}
		</ul>
	</li>
{{/each}}
</script>


<script type="text/x-handlebars-template" id="engine-options-template">
{{#each engine}}	
	 <tr>
	 	<td class="name-capitalize">{{@key}} </td> 
		<td>: {{this}}</td>
	</tr>
{{/each}}
</script>

<script type="text/x-handlebars-template" id="transmission-options-template">
{{#each transmission}}	
	 <tr>
	 	<td class="name-capitalize">{{@key}} </td> 
		<td>: {{this}}</td>
	 </tr>
{{/each}}
</script>


<script type="text/x-handlebars-template" id="steering-options-template">
	<tr>
	 	<td colspan="2"><strong>{{this.name}}</strong></td> 
	</tr>
	{{#each attributes}}	
		<tr>
			<td class="name-capitalize">{{this.name}} </td> 
			<td>: {{this.value}}</td>
		 </tr>		
	{{/each}}
	
</script>
                        