<div class="car-list">
    <table id="dahsboard_tb" class="table table-striped">
        <thead style="background-color: #808080; color: #fff;">
            <tr>
                <th class="col-md-2">Item</th>
                <th class="col-md-4">Details</th>
                <th class="col-md-2">End</th>
                <th class="col-md-2">Current Bid Offer</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
    Under Construction
</div>