<div class="row">
	<div class="col-md-5">
        <div id="car-main-image"><img id="car_main_image" src="https://media.ed.edmunds-media.com/jaguar/xf/2013/oem/2013_jaguar_xf_sedan_30-awd_fq_oem_2_400.jpg" /></div>
    </div>    
    <div class="col-md-6">
    	<div class="c-info">
                <h3 id="car-name">Jaguar XF</h3>
                <h5 id="transmission">Supercharged AUTOMATIC</h5>
                
                <br clear="all" />
                    <div class="row">
                        <div class="col-md-6">
                            <p>Exterior Color: <span id="exterior_color_<?php echo $this->order_id;?>">-</span></p>

                        </div>
                        <div class="col-md-6">
                            <p>Interior Color: <span id="interior_color_<?php echo $this->order_id;?>">-</span></p>
                        </div>
                    </div>
                    
               <br clear="all" />
                <div class="row">
                    <div class="col-md-6">
                        <p class="as_configured">As Configured</p>
						<span class="as_configured_price">$0.00</span>
                    </div>
                    <div class="col-md-6">
                        <p class="finance_estimate">Finance Estimate</p>
                        <span class="pull-left finance_estimate_price">$551</span><span class="seventy_two_months">per month<br />for 72 months</span>
                    </div>
                </div> 
                <br clear="all" />
                <a href="#" class="btn btn-default" style="font-size:12px;line-height:120%;color:rgb(136,136,136);text-align:left;">View Details</a>
                    
        </div>   
    </div>
       <br clear="all" />
       
       <p class="best_price_offer">Best Price Offer</p>
       <div class="current_bid_box">
       		<div class="row">
                <div class="col-md-6">
                    <p>Current Bid : <span class="current_bid">$0.00</span> <span class="bid_count">0 Bids</span></p>
                </div>
                <div class="col-md-6">
                    <p>
                    	Finance Estimate : <span class="finance_estimate_price" style="margin-left:15px;">$551</span>
                    	<span class="seventy_two_months">per month for 72 months</span>
                    </p>
                </div>
            </div>
       </div>
       <br clear="all" />
       <table id="poster-view-list-tb" class="table table-condensed table-striped">
        <thead>
            <tr>
                <th class="col-md-2">Rank</th>
                <th class="col-md-4">Bid Offer</th>
                <th class="col-md-2">Finance Offer</th>
                <th class="col-md-2">Date</th>
                <th class="col-md-2">&nbsp;</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
       
</div>