<div class="car-list">
    <table id="dahsboard_tb" class="table table-striped">
        <thead style="background-color: #808080; color: #fff;">
            <tr>
                <th class="col-md-2">Item</th>
                <th class="col-md-4">Details</th>
                <th class="col-md-2">End</th>
                <th class="col-md-2">Current Bid Offer</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<script type="text/x-handlebars-template" id="user-dashboard-list-template">
	<tr>
		<td>
			{{order_id}}<br />
			{{order_date}}<br />
			{{style_id}}<br />
			{{zipcode}}<br />
			{{status}}<br />
			{{date_diff}}<br />
			{{duration}}
		</td>
		<td>
			<h4 id="car_name_{{order_id}}">-</h4>
			<p>Engine: <span id="engine_{{order_id}}">-</span></p>
			<p>Transmission: <span id="transmission_{{order_id}}">-</span></p>
			<p>Exterior Color: <span id="exterior_color_{{order_id}}">-</span></p>
			<p>Interior Color: <span id="interior_color_{{order_id}}">-</span></p>
			<button type="submit" class="btn btn-primary">View Details</button>
		</td>
		<td><p class="con-bid">-</p></td>
		<td><p class="c-bid"><span>-</span></p></td>
	</tr>
</script>
