<input type="hidden" name="user_page" id="user_page" value="dashboard"/>
<div class="car-list">
    <table id="dahsboard_tb" class="table">
        <thead style="background-color: #808080; color: #fff;">
            <tr>
                <th class="col-md-2">Item</th>
                <th class="col-md-4">Details</th>
                <th class="col-md-2">End</th>
                <th class="col-md-2">Current Bid Offer</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<script type="text/x-handlebars-template" id="user-dashboard-list-template">
	<tr>
		<td>
			<img id="car_main_image_{{order_id}}" />
			<!--
			{{order_id}}<br />
			{{order_date}}<br />
			{{style_id}}<br />
			{{zipcode}}<br />
			{{status}}<br />
			{{date_diff}}<br />
			{{duration}}
			-->
		</td>
		<td>
			<h4 id="car_name_{{order_id}}">-</h4>
			<p>{{order_date_str}} {{date_diff}}</p>
			<p id="total_baseInvoice_{{order_id}}" style="font-size:20px; line-height:120%; color:rgb(136,136,136); text-align:left; margin-top:17px;" >$0</p>
			<p><strong>MSRP Price</strong></p>
			
		</td>
		<td><p style="font-size:13px;font-weight:bold;line-height:120%;color:rgb(119,119,119);text-align:left;">{{days_left}}</p></td>
		<td>
			<p style="font-size:20px; line-height:120%; color:rgb(139,196,63); text-align:left;">$0</p>
			<p style="font-size:13px;line-height:120%;color:rgb(119,119,119);text-align:left;margin-top:10px;">0 Bids</p>
			<p style=";margin-top:10px;"><a href="/user/order/{{order_id}}" class="btn btn-default" style="font-size:12px;line-height:120%;color:rgb(136,136,136);text-align:left;">View Details</a></p>
		</td>
	</tr>
</script>

<script type="text/x-handlebars-template" id="exterior-options-template">
	<li style="margin-top:10px;">{{name}} <span class="price" style="float:right; margin-right:20px;">+ ${{price.baseMSRP}}</span></li>
</script>

<script type="text/x-handlebars-template" id="interior-options-template">
	<li style="margin-top:10px;">{{name}} <span class="price" style="float:right; margin-right:20px;">+ ${{price.baseMSRP}}</span></li>
</script>

